apiVersion: v1
kind: Service
metadata:
  name: http-memcache-entry
spec:
  type: NodePort
  selector:
    app: http-memcache
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
